openapi: 3.0.3
info:
    title: 'Buser Rent Car Nasional'
    description: ''
    version: 1.0.0
servers:
    -
        url: 'http://api.brn.com'
paths:
    /api/point/missions:
        get:
            summary: 'Mendapatkan list data misi.'
            description: ''
            parameters:
                -
                    in: header
                    name: Authorization
                    description: ''
                    example: 'Bearer {YOUR_AUTH_KEY}'
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    data: [{ id: 1, active: true, name: 'Daily Check In', description: 'Check In setiap hari', points: 10, parent_id: null, childrens: [] }, { id: 4, active: true, name: Grades, description: null, points: 100, parent_id: null, childrens: [{ id: 5, active: true, name: Excellent, description: null, points: 600, parent_id: 4, childrens: [{ id: 6, active: true, name: Excellent, description: null, points: 100, parent_id: 5, childrens: [] }] }] }]
                                    links: { first: 'https://api.brn.com/api/point/missions?page=1', last: null, prev: null, next: null }
                                    meta: { current_page: 1, from: 1, path: 'https://api.brn.com/api/point/missions', per_page: 10, to: 10 }
                                properties:
                                    data: { type: array, example: [{ id: 1, active: true, name: 'Daily Check In', description: 'Check In setiap hari', points: 10, parent_id: null, childrens: [] }, { id: 4, active: true, name: Grades, description: null, points: 100, parent_id: null, childrens: [{ id: 5, active: true, name: Excellent, description: null, points: 600, parent_id: 4, childrens: [{ id: 6, active: true, name: Excellent, description: null, points: 100, parent_id: 5, childrens: [] }] }] }], items: { type: object } }
                                    links: { type: object, example: { first: 'https://api.brn.com/api/point/missions?page=1', last: null, prev: null, next: null } }
                                    meta: { type: object, example: { current_page: 1, from: 1, path: 'https://api.brn.com/api/point/missions', per_page: 10, to: 10 } }
            tags:
                - Point
    /api/point/histories:
        get:
            summary: 'Mendapatkan list data histori point.'
            description: ''
            parameters:
                -
                    in: header
                    name: Authorization
                    description: ''
                    example: 'Bearer {YOUR_AUTH_KEY}'
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    data: [{ id: 2, active: true, name: 'Completed Lesson', description: null, points: 100, get_it_at: '2021-05-29T19:46:48.000000Z' }, { id: 1, active: true, name: 'Daily Check In', description: 'Check In setiap hari', points: 10, get_it_at: '2021-04-29T19:46:48.000000Z' }]
                                    links: { first: 'https://api.brn.com/api/point/missions?page=1', last: null, prev: null, next: null }
                                    meta: { current_page: 1, from: 1, path: 'https://api.brn.com/api/point/missions', per_page: 10, to: 10 }
                                properties:
                                    data: { type: array, example: [{ id: 2, active: true, name: 'Completed Lesson', description: null, points: 100, get_it_at: '2021-05-29T19:46:48.000000Z' }, { id: 1, active: true, name: 'Daily Check In', description: 'Check In setiap hari', points: 10, get_it_at: '2021-04-29T19:46:48.000000Z' }], items: { type: object } }
                                    links: { type: object, example: { first: 'https://api.brn.com/api/point/missions?page=1', last: null, prev: null, next: null } }
                                    meta: { type: object, example: { current_page: 1, from: 1, path: 'https://api.brn.com/api/point/missions', per_page: 10, to: 10 } }
            tags:
                - Point
    /api/ping:
        get:
            summary: 'Ping the server.'
            description: ''
            parameters:
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: ''
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    status: ok
                                    timestamp: '2021-04-30T11:59:51.367557Z'
                                    host: 127.0.0.1
                                properties:
                                    status: { type: string, example: ok }
                                    timestamp: { type: string, example: '2021-04-30T11:59:51.367557Z' }
                                    host: { type: string, example: 127.0.0.1 }
            tags:
                - Server
            security: []
components:
    securitySchemes:
        default:
            type: http
            scheme: bearer
            description: ''
security:
    -
        default: []
